### ISSUE TITLE
Please tag the current version

### ISSUE THREAD

**Issue by johannesring** [hplgit/preprocess#8]
Please add a tag for the current version.

**Comment by johannesring** [comment]
Something like this:

```
git tag -a preprocess-1.2.2 -m 'preprocess version 1.2.2'
git push origin preprocess-1.2.2
```

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by johannesring** [comment]
I'm not sure if anyone have permissions to update this repository. @KGHustad - do you know? If not, I can fork it and maintain it for now.

**Comment by KGHustad** [comment]
Well, I don't have push access to this repository, and I don't know anyone else who has. Forking sounds like the best option.

**Comment by johannesring** [comment]
Thanks @KGHustad. I have fixed this issue in my fork: https://github.com/johannesring/preprocess
